# Nav2 全局路径规划器 — NavFn (2D)
planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    use_sim_time: false
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.15
      use_astar: false
      allow_unknown: true